CREATE TABLE IF NOT EXISTS tenant (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT,
  actor VARCHAR(100),
  action VARCHAR(100) NOT NULL,
  target VARCHAR(200),
  metadata_json JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE knowledge_base ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE knowledge_document ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE knowledge_chunk ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE prompt_template ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE workflow_run ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
ALTER TABLE eval_run ADD COLUMN IF NOT EXISTS tenant_id BIGINT;
